Move issue deposit vars to separate contract
OpenQDev/OpenQ-Contracts pull request #15
Opened 2021-04-10 13:30 UTC by JasperTimm

The main aim of this PR is to move the variables related to issues and deposits to a separate contract: `IssueDepositStorage.sol`, similar to other contracts, so that the main Octobay contract can be redeployed without changing the previous issues.

An additional benefit of doing this is that the main Octobay contract now comes in at < 24KB in compiled size, so we can deploy it again, without having to comment anything out. We should consider other changes in the future though to make it more manageable. Reducing the OracleStorage wrapper functions would help if we call it directly.

NOTE: A big change here is that ETH for deposits is now forwarded from the main Octobay contract to the IssueDepositStorage contract and paid out from there. If we aren't happy with this we can also change to keep the ETH in Octobay main.

2021-04-16 13:22 UTC, mktcode commented
> NOTE: A big change here is that ETH for deposits is now forwarded from the main Octobay contract to the IssueDepositStorage contract and paid out from there. If we aren't happy with this we can also change to keep the ETH in Octobay main.

Absolutely fine for now.

2021-04-19 21:20 UTC, mktcode requested changes
See comments below.

2021-04-19 21:20 UTC, mktcode commented on contracts/Octobay.sol
> +    //TODO: These methods are all wrappers, can we call OracleStorage directly?
The issue here is the `onlyOctobay` modifier in the `OracleStorage` contract. How would you manage access to those methods otherwise?

2021-04-19 21:20 UTC, mktcode commented on contracts/Octobay.sol
> +    mapping(string => uint256) public issuePins;
That's this functionality to "pin" issues to the top of the pinboard in the app. I think you can just remove it for now. Its not used.

2021-04-19 21:20 UTC, mktcode commented on contracts/Octobay.sol
> +        issueDepositStorage.depositEthForGithubUser{value: msg.value}(_githubUserId, msg.sender);
You should maybe rename it to simply "DepositStorage". And it handles deposits for users and issues and later also for projects or orgs probably. Not sure if we should then also split this up but I think one contract is good for now.

2021-04-19 21:20 UTC, mktcode commented on contracts/Octobay.sol
> +        emit IssueDepositEvent(msg.sender, msg.value, _issueId, issueDepositId);
In the other places we emit events in the respective `OctobayStorage` contract. Should be the same here I'd say.

2021-04-21 10:15 UTC, JasperTimm commented on contracts/Octobay.sol
> +    //TODO: These methods are all wrappers, can we call OracleStorage directly?
We'd use `onlyOwner` in `OracleStorage` instead, which is the same as it is now really, as that's how the functions are protected within `Octobay.sol` itself.

2021-04-21 10:15 UTC, JasperTimm commented on contracts/Octobay.sol
> +    //TODO: These methods are all wrappers, can we call OracleStorage directly?
We'd use `onlyOwner` in `OracleStorage` instead, which is the same as it is now really, as that's how the functions are protected within `Octobay.sol` itself.

2021-04-21 10:47 UTC, JasperTimm commented
@mktcode - fixed conflicts and updated from comments

2021-04-21 11:27 UTC, mktcode commented on contracts/Octobay.sol
> +    //TODO: These methods are all wrappers, can we call OracleStorage directly?
Hm true.... Then we can just make direct calls for now I guess... and remove the wrapper functions. Maybe in the future we'll have admin NFTs for Octobay itself. :D

2021-04-21 11:37 UTC, JasperTimm commented on contracts/Octobay.sol
> +    //TODO: These methods are all wrappers, can we call OracleStorage directly?
It does mean the Frontend needs to keep track of another contract, but I guess that's not a big deal.

I'll update this PR to remove them then.

2021-04-21 12:10 UTC, mktcode requested changes
Oh and if you are removing stuff right now anyway... maybe also throw away everything related to twitter. Will not be relevant for v0.1 and I think it's better not to have any dead code anyway. We have everything archived here so...

2021-04-21 12:10 UTC, mktcode commented on contracts/Octobay.sol
> +    //TODO: These methods are all wrappers, can we call OracleStorage directly?
Nope, that's fine. Done in 5 minutes. So yes, remove them. I'll merge this then and adjust the frontend and update our subgraph.

2021-04-21 14:28 UTC, mktcode approved these changes

2021-04-21 14:29 UTC, merged