Add implementation for governance token template and token factory
OpenQDev/OpenQ-Contracts pull request #8
Opened 2021-03-17 18:40 UTC by JasperTimm

This is intended to cover: 
#4 
#5 

Things to consder:

- Do we want to explicitly disable the allowance (approval) related functions inherited from ERC20? (Probably)
- Where are we storing the list of Tokens created? In the factory or a separate contract?

TO DO:

- [ ] Add appropriate events to track token creation
- [ ] implement `balanceOfAt(uint256 blocknumber)`

2021-03-17 19:20 UTC, mktcode requested changes
Almost perfect! Just the one thing with the event and that's it for now. If we need more changes, we'll handle them in their own issues.

2021-03-17 19:20 UTC, mktcode commented on contracts/OctobayGovTokenFactory.sol
> +    event NewTokenEvent(string name, string symbol);
This event should also contain the address. That way our subgraph does not need to do any extra work.

2021-03-17 19:20 UTC, mktcode commented on contracts/OctobayGovToken.sol
> +}
File should end with empty line. (Don't know who invented this convention or why but even GitHub suggestes it :D)
I still have to set up proper linting for this and other repos.

2021-03-17 19:22 UTC, mktcode commented on contracts/OctobayGovToken.sol
> +}
The other change is obviously the more important one. Don't mind this one. xD I was just wondering why even GitHub wants us to put an empty line at the end. Anyway....

2021-03-18 14:35 UTC, JasperTimm commented
Ok, made a couple of changes:

- The new token event now includes the address of the newly created token.
- Stored the mapping of the org/repo path to the token address in the factory. I've left it as a string for now, as I'm not sure the factory needs to know whether it's an org or repo but we can obviously change it later.
- There's a function to update the org/repo (which I've named 'project' for now)

2021-03-19 13:51 UTC, JasperTimm commented
This can be closed without merging now, as the PR in #9 includes this.

2021-03-19 13:51 UTC, closed without merging